#include <stdio.h>
#include <stddef.h>
#include <sys/utsname.h>

#define S(s) do { \
	struct s _s; \
	printf("\tpublic static final class " #s " {\n"); \
	printf("\t\tpublic static final int sizeof = %d;\n", sizeof _s); \
} while (0)

#define SF(s, f) do { \
	struct s _s; \
	printf("\t\tpublic static final int[] " #f " = { %d, %d };\n", \
		offsetof(struct s, f), sizeof _s.f); \
} while (0)

#define ES() printf("\t}\n")

int main() {
	printf("package sys.user;\n\n");
	printf("/* generated by linuxconstants.c */\n");
	printf("public final class LinuxConstants {\n");
	S(utsname);
	SF(utsname, sysname);
	SF(utsname, nodename);
	SF(utsname, release);
	SF(utsname, version);
	SF(utsname, machine);
	ES();
	printf("}\n");
}
